name: Hosted Runners

on: ['workflow_dispatch']

jobs:
  test-xcode:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-13', 'macos-13-xlarge', 'macos-13-large']

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: List Simulators
        run: xcrun simctl list
      - name: Run Tests
        run: |
          time xcodebuild test -scheme TestSuite -destination 'OS=17.2,name=iPhone 15 Pro' -configuration "Automation"
