name: Hosted [Runner 13] [Host 13.4] [Guest 13.6] [Xcode 15.2]

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *'

jobs:
  test-xcode:
    runs-on: macos-13-large

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: List Simulators
        run: xcrun simctl list
      - name: Run Tests
        run: |
          time xcodebuild -scheme TestSuite -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' build-for-testing test-without-building
