on: ['workflow_dispatch']

jobs:
  test-xcode:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            'macos-13',
            'macos-12',
            'macos-13-xlarge',
            'macos-13-large',
            'macos-12-large',
          ]

    steps:
      - uses: actions/checkout@v3
      - run: xcrun simctl list
      - name: test
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app
          time xcodebuild test -scheme TestSuite -destination 'OS=17.0,name=iPhone 14 Pro' -configuration "Automation"
