name: Self Hosted Runners

on:
  workflow_dispatch:

  schedule:
    - cron: '*/20 * * * *'

jobs:
  test-xcode:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, macOS, ARM64, macos-13.6]]

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: List Simulators
        run: xcrun simctl list
      - name: Run Tests
        run: |
          time xcodebuild test -scheme TestSuite -destination 'OS=17.2,name=iPhone 15 Pro' -configuration "Automation"
      - name: Clean Cache
        run: |
          xcrun -k
          xcodebuild -alltargets clean
          rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
          rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang.$(whoami)/ModuleCache"
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ~/Library/Caches/com.apple.dt.Xcode/*
